# Use Node.js base image
FROM node:20-alpine AS builder

WORKDIR /app

# Copy package files
COPY package*.json ./
COPY prisma ./prisma/

# Install all dependencies including dev dependencies for build
RUN npm ci

# Copy source code
COPY . .

# Generate Prisma client and build project
RUN npx prisma generate
# RUN npm run prisma:seed
RUN npm run build

# Production stage
FROM node:20-alpine AS production

WORKDIR /app

ENV NODE_ENV=production

# Set build-time arguments for environment variables
ARG APP_NAME
ARG PORT
ARG VERSION
ARG DATABASE_URL
ARG JWT_ACCESS_TOKEN_SECRET
ARG JWT_ACCESS_TOKEN_EXPIRE
ARG JWT_REFRESH_TOKEN_SECRET
ARG JWT_REFRESH_TOKEN_EXPIRE
ARG TIMEZONE
ARG ENCRYPTION_KEY
ARG URL_AUTH
ARG URL_CONFIG
ARG URL_TRANSACTION
ARG URL_SETTLERECON
ARG CLIENT_AUTH_NAME
ARG CLIENT_AUTH_HOST
ARG CLIENT_AUTH_PORT
ARG CLIENT_CONFIG_NAME
ARG CLIENT_CONFIG_HOST
ARG CLIENT_CONFIG_PORT
ARG CLIENT_TRANSACTION_NAME
ARG CLIENT_TRANSACTION_HOST
ARG CLIENT_TRANSACTION_PORT
ARG CLIENT_SETTLERECON_NAME
ARG CLIENT_SETTLERECON_HOST
ARG CLIENT_SETTLERECON_PORT

# Set environment variables from build-time arguments
ENV APP_NAME=$APP_NAME
ENV PORT=$PORT
ENV VERSION=$VERSION
ENV DATABASE_URL=$DATABASE_URL
ENV JWT_ACCESS_TOKEN_SECRET=$JWT_ACCESS_TOKEN_SECRET
ENV JWT_ACCESS_TOKEN_EXPIRE=$JWT_ACCESS_TOKEN_EXPIRE
ENV JWT_REFRESH_TOKEN_SECRET=$JWT_REFRESH_TOKEN_SECRET
ENV JWT_REFRESH_TOKEN_EXPIRE=$JWT_REFRESH_TOKEN_EXPIRE
ENV TIMEZONE=$TIMEZONE
ENV ENCRYPTION_KEY=$ENCRYPTION_KEY
ENV URL_AUTH=$URL_AUTH
ENV URL_CONFIG=$URL_CONFIG
ENV URL_TRANSACTION=$URL_TRANSACTION
ENV URL_SETTLERECON=$URL_SETTLERECON
ENV CLIENT_AUTH_NAME=$CLIENT_AUTH_NAME
ENV CLIENT_AUTH_HOST=$CLIENT_AUTH_HOST
ENV CLIENT_AUTH_PORT=$CLIENT_AUTH_PORT
ENV CLIENT_CONFIG_NAME=$CLIENT_CONFIG_NAME
ENV CLIENT_CONFIG_HOST=$CLIENT_CONFIG_HOST
ENV CLIENT_CONFIG_PORT=$CLIENT_CONFIG_PORT
ENV CLIENT_TRANSACTION_NAME=$CLIENT_TRANSACTION_NAME
ENV CLIENT_TRANSACTION_HOST=$CLIENT_TRANSACTION_HOST
ENV CLIENT_TRANSACTION_PORT=$CLIENT_TRANSACTION_PORT
ENV CLIENT_SETTLERECON_NAME=$CLIENT_SETTLERECON_NAME
ENV CLIENT_SETTLERECON_HOST=$CLIENT_SETTLERECON_HOST
ENV CLIENT_SETTLERECON_PORT=$CLIENT_SETTLERECON_PORT

# Install only production dependencies
COPY --from=builder /app/package*.json ./
RUN npm ci --only=production && npm cache clean --force

# Copy built application and Prisma client
COPY --from=builder /app/dist ./dist
COPY --from=builder /app/node_modules/.prisma ./node_modules/.prisma
COPY --from=builder /app/node_modules/@prisma ./node_modules/@prisma

# Create non-root user for security
RUN addgroup -g 1001 -S nodejs
RUN adduser -S nestjs -u 1001

# Change ownership to non-root user
RUN chown -R nestjs:nodejs /app

USER nestjs

EXPOSE 3001

# Health check
HEALTHCHECK --interval=30s --timeout=3s --start-period=5s --retries=3 \
  CMD node dist/health-check.js || exit 1

CMD ["node", "dist/src/main.js"]
